// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnwcxsmldjosjleevevs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNud2N4c21sZGpvc2psZWV2ZXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzUwNTMsImV4cCI6MjA2NDExMTA1M30.6cqe8_bJqmDngTUQWeFqOjptM55-wkDAufN67ZYZmxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);